### PR TITLE
Support for blade and vuejs

### PR DESCRIPTION
**Pull request by ctf0**
support blade & vue

### CODE REVIEW

**Comment by ctf0** [comment]
not sure what you mean, but its working as expected so far.

however what i would really like to is the support for sass/scss

**Comment by anteprimorac** [comment]
For example currently for PHP and Blade templates if you have dynamic class attribute something like this `<div class="<?php echo implode(' ', ['class-1', 'class-2']); ?>` it won't evaluate that PHP script instead it will display end label something like `/.<?php.echo.implode...`. Currently, I don't know how hard it is to support this, but I will explore PHP and Vue.js language servers to see can we get useful information from them.

**Comment by anteprimorac** [comment]
@ctf0 what do you mean by support for sass/scss?

**Comment by ctf0** [comment]
aha okay, i think it will be hard to do that cuz its dynamic

for sass heres what i mean 
https://marketplace.visualstudio.com/items?itemName=charles-sanford.scss-block-comments

**Comment by anteprimorac** [comment]
@ctf0 currently the scope of this extension is to support only HTML end tags and anything beyond it will require an extension name change. I would like to polish current features and later I will see if this can be expanded on other languages.

**Comment by ctf0** [comment]
yeah yeah, i was talking about anew ext with the same functionality as the html tag

**Pull request merged**
